### ISSUE TITLE
Unexpected close tagline in sax.js

### ISSUE THREAD

**Issue by Saumyadip-Pramanik** [bamlab/react-native-make#21]
React Native 0.61.4
react-native-make: 1.0.3

Unexpected close tagLine: 30Column: 16Char: >    at error (../node_modules/sax/lib/sax.js:651:10)    at strictFail (../node_modules/sax/lib/sax.js:677:7)    at closeTag (../node_modules/sax/lib/sax.js:871:9)    at SAXParser.write (../node_modules/sax/lib/sax.js:1436:13)    at new XmlDocument (../node_modules/xmldoc/lib/xmldoc.js:261:15)    at readManifest (../node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:10)    at Object.projectConfig (../node_modules/@react-native-community/cli-platform-android/build/config/index.js:59:46)    at Object.get project [as project] (../node_modules/react-native/node_modules/@react-native-community/cli/build/tools/config/index.js:114:50)    at ../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/config/config.js:8:452    at Array.forEach (<anonymous>)

**Comment by yleflour** [comment]
Which node version are you using?
